### ISSUE TITLE
update site

### ISSUE THREAD

**Issue by bjmi** [Nodeclipse/zipeditor#1]
Please provide an update site for zipeditor of this repository.

Thanks in advance.

**Comment by paulvi** [comment]
It is already inside http://www.nodeclipse.org/updates/

Please ask on https://sourceforge.net/p/zipeditor for newer versions

**Comment by bjmi** [comment]
Can you mention this update-site in repository readme?

**Comment by paulvi** [comment]
I don't really understand what do you mean by "update-site in repository readme".
Can you give URL or make PR ?

**Comment by bjmi** [comment]
Please add a section in https://github.com/Nodeclipse/zipeditor/blob/master/README.md where the existing update site (http://www.nodeclipse.org/updates/) is listed.

**Comment by paulvi** [comment]
OK
